"""PDF generation for SCT Pre-Filing Claim Summaries.

Generates an official, publication-quality PDF summary of a claimant's
draft Small Claims Tribunals (SCT) filing in compliance with the
Singapore Courts' Guide on the Use of Generative AI.
"""

from __future__ import annotations

import io
from datetime import UTC, datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# Judicial Civic Palette (mirroring DESIGN.md)
PRIMARY_MAROON = colors.HexColor("#8B1D3D")
PRIMARY_CONTAINER = colors.HexColor("#F8F1F3")
TEXT_SLATE = colors.HexColor("#1E293B")
MUTED_SLATE = colors.HexColor("#526478")
BORDER_GRAY = colors.HexColor("#CBD5E1")
LIGHT_BG = colors.HexColor("#F8FAFC")
WARNING_AMBER = colors.HexColor("#D97706")


def generate_prefiling_pdf(case_data: dict[str, Any]) -> bytes:
    """Generate a high-quality PDF claim summary from validated case data."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title="SCT Pre-Filing Claim Summary",
        author="ClaimReady / ClaimBuddy",
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=16,
        leading=20,
        textColor=PRIMARY_MAROON,
    )

    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=14,
        textColor=TEXT_SLATE,
    )

    meta_style = ParagraphStyle(
        "DocMeta",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=MUTED_SLATE,
    )

    section_header_style = ParagraphStyle(
        "SectionHeader",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10.5,
        leading=14,
        textColor=PRIMARY_MAROON,
    )

    label_style = ParagraphStyle(
        "CellLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=12,
        textColor=TEXT_SLATE,
    )

    value_style = ParagraphStyle(
        "CellValue",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=TEXT_SLATE,
    )

    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=7.5,
        leading=10.5,
        textColor=MUTED_SLATE,
    )

    story = []

    # 1. Header Banner
    ref_num = case_data.get("reference_number") or f"DRAFT-{datetime.now(UTC).strftime('%Y%m%d%H%M')}"
    today_str = datetime.now(UTC).strftime("%d %b %Y")

    header_data = [
        [
            Paragraph("SMALL CLAIMS TRIBUNALS (SCT)", title_style),
            Paragraph(f"<b>Reference:</b> {ref_num}<br/><b>Date:</b> {today_str}", meta_style),
        ],
        [
            Paragraph("PRE-FILING CLAIM INTAKE SUMMARY (FORM 1 DRAFT)", subtitle_style),
            Paragraph("<b>Status:</b> Preparation Aid (Unofficial)", meta_style),
        ],
    ]
    header_table = Table(header_data, colWidths=[120 * mm, 54 * mm])
    header_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ALIGN", (1, 0), (1, -1), "RIGHT"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ]
        )
    )
    story.append(header_table)
    story.append(Spacer(1, 4 * mm))
    story.append(HRFlowable(width="100%", thickness=1.5, color=PRIMARY_MAROON, spaceAfter=4 * mm))

    # 2. Disclaimer Callout Box
    disclaimer_text = (
        "<b>Important Notice:</b> This document is a preparation draft generated by the ClaimReady assistance tool. "
        "It does not constitute legal advice and has not yet been filed in court. To commence formal proceedings, "
        "submit your verified claim through Singapore Courts' Community Justice and Tribunals System (CJTS)."
    )
    disclaimer_table = Table([[Paragraph(disclaimer_text, disclaimer_style)]], colWidths=[174 * mm])
    disclaimer_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), PRIMARY_CONTAINER),
                ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#E5D2D7")),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(disclaimer_table)
    story.append(Spacer(1, 5 * mm))

    # 3. Section 1: Claimant Details
    story.append(Paragraph("1. CLAIMANT PARTICULARS", section_header_style))
    story.append(Spacer(1, 1.5 * mm))

    claimant_data = [
        [
            Paragraph("Full Name (as in NRIC/Passport):", label_style),
            Paragraph(str(case_data.get("claimant_name") or "-"), value_style),
            Paragraph("NRIC / FIN:", label_style),
            Paragraph(str(case_data.get("claimant_nric") or "-"), value_style),
        ],
        [
            Paragraph("Email Address (Court Service):", label_style),
            Paragraph(str(case_data.get("claimant_email") or "-"), value_style),
            Paragraph("Contact / Phone:", label_style),
            Paragraph(str(case_data.get("claimant_phone") or "Provided on filing"), value_style),
        ],
    ]
    t_claimant = Table(claimant_data, colWidths=[45 * mm, 45 * mm, 38 * mm, 46 * mm])
    t_claimant.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_GRAY),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_GRAY),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(t_claimant)
    story.append(Spacer(1, 4.5 * mm))

    # 4. Section 2: Respondent Details
    story.append(Paragraph("2. RESPONDENT PARTICULARS", section_header_style))
    story.append(Spacer(1, 1.5 * mm))

    respondent_data = [
        [
            Paragraph("Full Name or Business Name:", label_style),
            Paragraph(str(case_data.get("respondent_name") or "-"), value_style),
        ],
        [
            Paragraph("Address for Service of Claim:", label_style),
            Paragraph(str(case_data.get("respondent_address") or "-"), value_style),
        ],
    ]
    t_respondent = Table(respondent_data, colWidths=[45 * mm, 129 * mm])
    t_respondent.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_GRAY),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_GRAY),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(t_respondent)
    story.append(Spacer(1, 4.5 * mm))

    # 5. Section 3: Claim Details
    story.append(Paragraph("3. CLAIM DETAILS & JURISDICTION", section_header_style))
    story.append(Spacer(1, 1.5 * mm))

    raw_amt = case_data.get("claim_amount")
    amt_display = f"SGD ${float(raw_amt):,.2f}" if raw_amt not in (None, "") else "-"

    claim_data = [
        [
            Paragraph("Nature of Claim:", label_style),
            Paragraph(str(case_data.get("nature_of_dispute") or "-"), value_style),
            Paragraph("Amount Claimed:", label_style),
            Paragraph(f"<b>{amt_display}</b>", value_style),
        ],
        [
            Paragraph("Date Dispute Arose:", label_style),
            Paragraph(str(case_data.get("date_of_cause_of_action") or "-"), value_style),
            Paragraph("Statutory Limitation:", label_style),
            Paragraph("Within 2 years (SCT Act s.5(4))", value_style),
        ],
    ]
    t_claim = Table(claim_data, colWidths=[45 * mm, 45 * mm, 38 * mm, 46 * mm])
    t_claim.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_GRAY),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_GRAY),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(t_claim)
    story.append(Spacer(1, 4.5 * mm))

    # 6. Section 4: Statement of Claim (Particulars)
    story.append(Paragraph("4. BRIEF STATEMENT OF CLAIM (PARTICULARS)", section_header_style))
    story.append(Spacer(1, 1.5 * mm))

    statement_text = str(case_data.get("particulars") or case_data.get("statement_of_claim") or "No statement provided.")
    t_statement = Table([[Paragraph(statement_text, value_style)]], colWidths=[174 * mm])
    t_statement.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.white),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_GRAY),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(t_statement)
    story.append(Spacer(1, 5 * mm))

    # 7. Section 5: Statutory Filing Checklist & Next Steps
    story.append(Paragraph("5. NEXT STEPS & MANDATORY FILING CHECKLIST", section_header_style))
    story.append(Spacer(1, 1.5 * mm))

    checklist_text = (
        "1. <b>Service of Documents:</b> You must serve a copy of the filed claim on the respondent within 7 days of lodging.<br/>"
        "2. <b>Mandatory Consultation:</b> Both parties will be directed to attend a mandatory Consultation session with a Registrar.<br/>"
        "3. <b>Supporting Evidence:</b> Prepare invoices, bank receipts, text message logs, and contracts to substantiate all amounts.<br/>"
        "4. <b>Civility Standard:</b> Pleadings must remain factual and free from abusive remarks to preserve tribunal credibility."
    )
    t_checklist = Table([[Paragraph(checklist_text, value_style)]], colWidths=[174 * mm])
    t_checklist.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_GRAY),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(t_checklist)
    story.append(Spacer(1, 6 * mm))

    # 8. Signature & Declaration Box
    sig_data = [
        [
            Paragraph("<b>Claimant Declaration:</b> I confirm that the details provided in this summary are true and accurate to the best of my knowledge.", disclaimer_style),
            Paragraph("<b>Signature:</b> ___________________________", value_style),
        ]
    ]
    t_sig = Table(sig_data, colWidths=[110 * mm, 64 * mm])
    t_sig.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
    story.append(t_sig)

    doc.build(story)
    return buffer.getvalue()
